title: Polarization in Public Opinion
description: >- # this means to ignore newlines until "baseurl:"
  RecSys, Computational Social Science, Credibility & Trust, Networks, Biases
# Build settings
theme: jekyll-theme-cayman
github:
  is_project_page: false
